version: '3'

services:
  netlifycms-example:
    image: netlifycms-example
    restart: always
    build:
      context: ./
    ports:
      - "3024:3000"
      - "3025:3025"
    env_file:
      - .env  
